move rook 10,1
attack rook archer-2
move pell 10,2
attack pell archer-2
move captain 10,4
wait captain
move dunstan 11,3
wait dunstan
move wren 10,3
wait wren
end
recall list
recall 3
threat pell
wait pell
threat dunstan
move captain 9,4
wait captain
move dunstan 11,3
wait dunstan
move wren 10,3
wait wren
end
move pell 12,2
attack pell archer-2
attack rook archer-2
move captain 12,3
wait captain
move wren 14,3
wait wren
threat dunstan
wait dunstan
end
