<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Ironwake.Sim</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ironwake.Core\Ironwake.Core.csproj" />
    <ProjectReference Include="..\Ironwake.Content\Ironwake.Content.csproj" />
  </ItemGroup>

</Project>
